name: Combined Workflow

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update_json:
    name: 更新JSON文件
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装依赖并生成JSON
        run: |
          pip install markdown
          python ToJson.py

      - name: 提交更改
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          git add .
          git commit -m ":sparkles: update JSON [skip ci]" || echo "无变更"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    name: 构建部署
    runs-on: ubuntu-latest
    needs: update_json
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 检出最新代码
      uses: actions/checkout@v4
      with:
        ref: main
        path: main-repo


    - name: 配置Node环境
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: 安装依赖
      working-directory: ./main-repo
      run: npm ci

    - name: 构建项目
      working-directory: ./main-repo
      run: npm run build

    - name: 保留域名配置
      working-directory: ./main-repo
      run: |
        mkdir -p dist  # 确保目录存在
        echo "main.seeku.site" > dist/CNAME
        ls -l dist/CNAME

    - name: 部署到Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./main-repo/dist
        force_orphan: true
        destination_branch: gh-pages