name: Build and Deploy

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当对 main 分支发起 PR 时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 使用 Node.js 18.x
        cache: 'npm'  # 缓存 npm 依赖

    - name: Install dependencies
      run: npm ci  # 使用 ci 而不是 install，这样可以确保使用 package-lock.json 中的精确版本

    - name: Build
      run: npm run build

    # 可选：保存构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/ 